//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.lamosa.sap.services.backorder {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://lamosa.com/A2A/PedidoSugerido", ConfigurationName="com.lamosa.sap.services.backorder.SI_BackOrder_Outbound")]
    public interface SI_BackOrder_Outbound {
        
        // CODEGEN: Generating message contract since the operation SI_BackOrder_Outbound is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        com.lamosa.sap.services.backorder.SI_BackOrder_OutboundResponse SI_BackOrder_Outbound(com.lamosa.sap.services.backorder.SI_BackOrder_OutboundRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lamosa.com/A2A/PedidoSugerido")]
    public partial class DT_BackOrder_request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string compayIdField;
        
        private string customerIdField;
        
        private DT_BackOrder_requestStore[] storesField;
        
        private DT_BackOrder_requestItem[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CompayId {
            get {
                return this.compayIdField;
            }
            set {
                this.compayIdField = value;
                this.RaisePropertyChanged("CompayId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Store", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_BackOrder_requestStore[] Stores {
            get {
                return this.storesField;
            }
            set {
                this.storesField = value;
                this.RaisePropertyChanged("Stores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_BackOrder_requestItem[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://lamosa.com/A2A/PedidoSugerido")]
    public partial class DT_BackOrder_requestStore : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string storeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string StoreId {
            get {
                return this.storeIdField;
            }
            set {
                this.storeIdField = value;
                this.RaisePropertyChanged("StoreId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lamosa.com/A2A/PedidoSugerido")]
    public partial class DT_BackOrder_response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string compayIdField;
        
        private string customerIdField;
        
        private string eRRORField;
        
        private DT_BackOrder_responseStore[] storesField;
        
        private DT_BackOrder_responseItem[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CompayId {
            get {
                return this.compayIdField;
            }
            set {
                this.compayIdField = value;
                this.RaisePropertyChanged("CompayId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
                this.RaisePropertyChanged("ERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Store", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_BackOrder_responseStore[] Stores {
            get {
                return this.storesField;
            }
            set {
                this.storesField = value;
                this.RaisePropertyChanged("Stores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_BackOrder_responseItem[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://lamosa.com/A2A/PedidoSugerido")]
    public partial class DT_BackOrder_responseStore : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string storeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string StoreId {
            get {
                return this.storeIdField;
            }
            set {
                this.storeIdField = value;
                this.RaisePropertyChanged("StoreId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://lamosa.com/A2A/PedidoSugerido")]
    public partial class DT_BackOrder_responseItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itemIdField;
        
        private string itemCustomerIdField;
        
        private string itemDescField;
        
        private string inventoryPendingField;
        
        private string unitOfMeasureField;
        
        private string convertionValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
                this.RaisePropertyChanged("ItemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ItemCustomerId {
            get {
                return this.itemCustomerIdField;
            }
            set {
                this.itemCustomerIdField = value;
                this.RaisePropertyChanged("ItemCustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ItemDesc {
            get {
                return this.itemDescField;
            }
            set {
                this.itemDescField = value;
                this.RaisePropertyChanged("ItemDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string InventoryPending {
            get {
                return this.inventoryPendingField;
            }
            set {
                this.inventoryPendingField = value;
                this.RaisePropertyChanged("InventoryPending");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string UnitOfMeasure {
            get {
                return this.unitOfMeasureField;
            }
            set {
                this.unitOfMeasureField = value;
                this.RaisePropertyChanged("UnitOfMeasure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ConvertionValue {
            get {
                return this.convertionValueField;
            }
            set {
                this.convertionValueField = value;
                this.RaisePropertyChanged("ConvertionValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://lamosa.com/A2A/PedidoSugerido")]
    public partial class DT_BackOrder_requestItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itemIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
                this.RaisePropertyChanged("ItemId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_BackOrder_OutboundRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://lamosa.com/A2A/PedidoSugerido", Order=0)]
        public com.lamosa.sap.services.backorder.DT_BackOrder_request MT_BackOrder_request;
        
        public SI_BackOrder_OutboundRequest() {
        }
        
        public SI_BackOrder_OutboundRequest(com.lamosa.sap.services.backorder.DT_BackOrder_request MT_BackOrder_request) {
            this.MT_BackOrder_request = MT_BackOrder_request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_BackOrder_OutboundResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://lamosa.com/A2A/PedidoSugerido", Order=0)]
        public com.lamosa.sap.services.backorder.DT_BackOrder_response MT_BackOrder_response;
        
        public SI_BackOrder_OutboundResponse() {
        }
        
        public SI_BackOrder_OutboundResponse(com.lamosa.sap.services.backorder.DT_BackOrder_response MT_BackOrder_response) {
            this.MT_BackOrder_response = MT_BackOrder_response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SI_BackOrder_OutboundChannel : com.lamosa.sap.services.backorder.SI_BackOrder_Outbound, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SI_BackOrder_OutboundClient : System.ServiceModel.ClientBase<com.lamosa.sap.services.backorder.SI_BackOrder_Outbound>, com.lamosa.sap.services.backorder.SI_BackOrder_Outbound {
        
        public SI_BackOrder_OutboundClient() {
        }
        
        public SI_BackOrder_OutboundClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_BackOrder_OutboundClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_BackOrder_OutboundClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_BackOrder_OutboundClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.lamosa.sap.services.backorder.SI_BackOrder_OutboundResponse com.lamosa.sap.services.backorder.SI_BackOrder_Outbound.SI_BackOrder_Outbound(com.lamosa.sap.services.backorder.SI_BackOrder_OutboundRequest request) {
            return base.Channel.SI_BackOrder_Outbound(request);
        }
        
        public com.lamosa.sap.services.backorder.DT_BackOrder_response SI_BackOrder_Outbound(com.lamosa.sap.services.backorder.DT_BackOrder_request MT_BackOrder_request) {
            com.lamosa.sap.services.backorder.SI_BackOrder_OutboundRequest inValue = new com.lamosa.sap.services.backorder.SI_BackOrder_OutboundRequest();
            inValue.MT_BackOrder_request = MT_BackOrder_request;
            com.lamosa.sap.services.backorder.SI_BackOrder_OutboundResponse retVal = ((com.lamosa.sap.services.backorder.SI_BackOrder_Outbound)(this)).SI_BackOrder_Outbound(inValue);
            return retVal.MT_BackOrder_response;
        }
    }
}
