//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.lamosa.sap.services.itemmaster {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://lamosa.com/A2A/PedidoSugerido", ConfigurationName="com.lamosa.sap.services.itemmaster.SI_ItemMaster_Outbound")]
    public interface SI_ItemMaster_Outbound {
        
        // CODEGEN: Generating message contract since the operation SI_ItemMaster_Outbound is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        com.lamosa.sap.services.itemmaster.SI_ItemMaster_OutboundResponse SI_ItemMaster_Outbound(com.lamosa.sap.services.itemmaster.SI_ItemMaster_OutboundRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lamosa.com/A2A/PedidoSugerido")]
    public partial class DT_ItemMaster_request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string compayIdField;
        
        private string customerIdField;
        
        private DT_ItemMaster_requestItem[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CompayId {
            get {
                return this.compayIdField;
            }
            set {
                this.compayIdField = value;
                this.RaisePropertyChanged("CompayId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_ItemMaster_requestItem[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://lamosa.com/A2A/PedidoSugerido")]
    public partial class DT_ItemMaster_requestItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itemDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ItemDesc {
            get {
                return this.itemDescField;
            }
            set {
                this.itemDescField = value;
                this.RaisePropertyChanged("ItemDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lamosa.com/A2A/PedidoSugerido")]
    public partial class DT_ItemMaster_response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string compayIdField;
        
        private string customerIdField;
        
        private DT_ItemMaster_responseItem[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CompayId {
            get {
                return this.compayIdField;
            }
            set {
                this.compayIdField = value;
                this.RaisePropertyChanged("CompayId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_ItemMaster_responseItem[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://lamosa.com/A2A/PedidoSugerido")]
    public partial class DT_ItemMaster_responseItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itemIdField;
        
        private string itemCustomerIdField;
        
        private string itemDescField;
        
        private string qualityIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
                this.RaisePropertyChanged("ItemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ItemCustomerId {
            get {
                return this.itemCustomerIdField;
            }
            set {
                this.itemCustomerIdField = value;
                this.RaisePropertyChanged("ItemCustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ItemDesc {
            get {
                return this.itemDescField;
            }
            set {
                this.itemDescField = value;
                this.RaisePropertyChanged("ItemDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string QualityId {
            get {
                return this.qualityIdField;
            }
            set {
                this.qualityIdField = value;
                this.RaisePropertyChanged("QualityId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ItemMaster_OutboundRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://lamosa.com/A2A/PedidoSugerido", Order=0)]
        public com.lamosa.sap.services.itemmaster.DT_ItemMaster_request MT_ItemMaster_request;
        
        public SI_ItemMaster_OutboundRequest() {
        }
        
        public SI_ItemMaster_OutboundRequest(com.lamosa.sap.services.itemmaster.DT_ItemMaster_request MT_ItemMaster_request) {
            this.MT_ItemMaster_request = MT_ItemMaster_request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ItemMaster_OutboundResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://lamosa.com/A2A/PedidoSugerido", Order=0)]
        public com.lamosa.sap.services.itemmaster.DT_ItemMaster_response MT_ItemMaster_response;
        
        public SI_ItemMaster_OutboundResponse() {
        }
        
        public SI_ItemMaster_OutboundResponse(com.lamosa.sap.services.itemmaster.DT_ItemMaster_response MT_ItemMaster_response) {
            this.MT_ItemMaster_response = MT_ItemMaster_response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SI_ItemMaster_OutboundChannel : com.lamosa.sap.services.itemmaster.SI_ItemMaster_Outbound, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SI_ItemMaster_OutboundClient : System.ServiceModel.ClientBase<com.lamosa.sap.services.itemmaster.SI_ItemMaster_Outbound>, com.lamosa.sap.services.itemmaster.SI_ItemMaster_Outbound {
        
        public SI_ItemMaster_OutboundClient() {
        }
        
        public SI_ItemMaster_OutboundClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ItemMaster_OutboundClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ItemMaster_OutboundClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ItemMaster_OutboundClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.lamosa.sap.services.itemmaster.SI_ItemMaster_OutboundResponse com.lamosa.sap.services.itemmaster.SI_ItemMaster_Outbound.SI_ItemMaster_Outbound(com.lamosa.sap.services.itemmaster.SI_ItemMaster_OutboundRequest request) {
            return base.Channel.SI_ItemMaster_Outbound(request);
        }
        
        public com.lamosa.sap.services.itemmaster.DT_ItemMaster_response SI_ItemMaster_Outbound(com.lamosa.sap.services.itemmaster.DT_ItemMaster_request MT_ItemMaster_request) {
            com.lamosa.sap.services.itemmaster.SI_ItemMaster_OutboundRequest inValue = new com.lamosa.sap.services.itemmaster.SI_ItemMaster_OutboundRequest();
            inValue.MT_ItemMaster_request = MT_ItemMaster_request;
            com.lamosa.sap.services.itemmaster.SI_ItemMaster_OutboundResponse retVal = ((com.lamosa.sap.services.itemmaster.SI_ItemMaster_Outbound)(this)).SI_ItemMaster_Outbound(inValue);
            return retVal.MT_ItemMaster_response;
        }
    }
}
